sudo: required
services:
  - docker

before_install:
  - docker build -t engsmar/docker-react -f Dockerfile.dev .

script:
  - docker run engsmar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-us-east-2-259056384165"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"